version: "3"
services:
  app:
    build: .
    restart: on-failure
    networks:
      - mynetwork
    volumes:
      - ./log/app/:/var/log/app/
    depends_on:
      - mysql
      - redis
    env_file:
      - ./.env
    ports:
    - "8000:8000"

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    networks:
      - mynetwork
    volumes:
      - ./data/mysql:/var/lib/mysql
    env_file:
      - ./.env

  redis:
    image: redis:5.0-alpine
    restart: always
    networks:
      - mynetwork

networks:
  mynetwork: